### ISSUE TITLE
g:XkbSwitchILayout and g:XkbSwitchNLayout

### ISSUE THREAD

**Issue by abcdw** [lyokha/vim-xkbswitch#10]
При установке этих переменных одновременно работает, только первая из установленных.
let g:XkbSwitchILayout = 'us(dvp)'
let g:XkbSwitchNLayout = 'us(dvp)'

**Comment by lyokha** [comment]
Все-таки я добавил *безусловную* раскладку в Insert mode как фикс для проблемы #24. Оказывается, эта фича востребована! Смотрите обновление секции *Default layouts* в README.
