### ISSUE TITLE
Only switching when going back to normal

### ISSUE THREAD

**Issue by yunake** [lyokha/vim-xkbswitch#24]
Really cool idea! Is there a way to *not* switch back to last active layout when going back to insert/select modes? I want to only switch back to `us` automatically when going to normal. Ideally I would like to set this on a per-buffer basis with `aucmd Filetype` or custom mappings. Is this possible?

**Comment by lyokha** [comment]
I am not sure that I understood this well. Do you mean pre-defined, unconditional layout for Insert mode? Or simply not doing anything when switching to Insert mode (i.e. this will normally mean that original Insert mode layout after switching to it will always be ``us``)?

**Comment by lyokha** [comment]
Try this as shown in the commit message example, but be aware that *momental* switching from-and-to Insert mode (like with Insert mode command ``Ctrl-O`` and all sorts of selections) will make current Insert mode layout lost. Unfortunately I cannot save current layout in these cases as soon as vim has no notion of *momental mode switches*.

**Comment by yunake** [comment]
хмм, если я правильно понимаю, этот autocmd поменяет раскладку при возвращении в insert-mode безусловно но "xx". это немного не то. попытаюсь обьяснить.

я как каждый опытный пользователь вима живу в normal mode и захожу в insert mode только для коротких берстов набора текста. все-таки большая часть времени — это редактирование а не набор. я также работаю с многоязыковыми файлами и использую больше двух раскладок в иксах, в том числе ru(ruu) и us(altgr-intl), а также compose и third-level keys. единственное чего мне не хватает — автоматического перехода на us при выходе в нормал моуд. ваш плагин отлично с этим справляется!

но он к сожалению также меняет раскладку на последнию использованную при входе в инсерт — я понимаю, что это by design. но я в инсерте часто в мелких фрагментах, через cin( и т.п., с непонятно каким языком. в итоге этот функционал очень сбивает, проще вручную в нормале на английский переключаться чем помнить в какой раскладке ты последний раз был. мне хотелось бы как-то отключить это, т.е. просто не трогать раскладку при переходе в инсерт. просто выставлять конкретную как в этом патче не вариант потому что не ясно в каком фрагменте я буду и какой язык будет нужен. можно как-то вообще просто не трогать раскладку при переходе в инсерт моуд? если нет, то этот патч тоже не самый плохой вариант, буду устанавливать эти аутоцмд на самый популярный язык в каждом конкретном filetype, и еще кастомную команду для оверрайда запилю.

**Comment by lyokha** [comment]
Ок, в случае установки этой переменной в пустое значение вы получите желаемое поведение. Попробуйте последнюю версию плагина.

**Comment by yunake** [comment]
уии, спасибо!
