### ISSUE TITLE
Не работает (не получилось настроить?) на Ubuntu 16.04

### ISSUE THREAD

**Issue by gyermolenko** [lyokha/vim-xkbswitch#28]
Пишу в инсерт моде текст на русском, выхожу в нормал мод - расскладка остаётся русской. 
Настройки:
let g:XkbSwitchEnabled = 1 
let g:XkbSwitchLib = '/usr/lib/libxkbswitch.so'
let g:XkbSwitchILayout = 'ru'
let g:XkbSwitchNLayout = 'us'

libxkbswitch.so с правами chmod +x

**Comment by lyokha** [comment]
а сам xkb-switch работает из командной строки? Попробуйте

```vim
xkb-switch -s ru
xkb-switch -s us
```

**Comment by gyermolenko** [comment]
хм. `xkb-switch -s ru` выдал 
Group ru' is not supported by current layout. Try xkb-switch -l

А переключаюсь на русский я таким образом обычно:
setxkbmap -layout ru

**Comment by lyokha** [comment]
Если не работает, то и плагин не будет работать, поскольку он использует библиотеку из ``xkb-switch``. Попробуйте зафайлить баг на ``xkb-switch`` или найти уже существующий.

**Comment by lyokha** [comment]
А что, кстати, выдает ``xkb-switch -l``?

**Comment by gyermolenko** [comment]
> А что, кстати, выдает xkb-switch -l?
только us

Пока что всё указывает не на баг, а на то, что я что-то недонастроил (системно, в xkb-switch или ещё где)

**Comment by gyermolenko** [comment]
**TLDR** порешал, это какой-то конфликт с setxkbmap. Извините за беспокойство, в виме всё заработало.)

**Преистория**: Я пользуюсь кастомными шортатами на переключение языков, когда-то нагуглил переключать командой `setxkbmap -layout us` (us/ua etc) что и работало успешно до сегодня.
В данной ситуации в системе, в настройках Layouts список языков может быть вообще любым, setxkbmap это не волнует.
При включённом русском `xkb-switch -l ` выдавал только ru, при включённом англ - только us. Переключение через xkb-switch -s xx выдавало ошибку.

**Решение:** 
- переназначил шоткаты с setxkbmap на xkb-switch
- удалил-добавил заново в системных настройках russian layout

**Comment by lyokha** [comment]
тогда я закрываю
