### ISSUE TITLE
"No mappings found" error

### ISSUE THREAD

**Issue by zdm** [lyokha/vim-xkbswitch#31]
Hi.

I am using vim 8 under windows 10.

Here is my config:
```
let g:XkbSwitchEnabled = 1
let g:XkbSwitchIMappings = ['ru']
let g:XkbSwitchIMappingsSkipFt = ['tex']
let g:XkbSwitchNLayout = 'US'
let g:XkbSwitchILayout = 'US'
```

When I am starting vim I constantly see this error message, duplicated many times.

```
...
No mappings found
No mappings found
No mappings found
No mappings found
...
```

Could you, pls, tell me how to avoid this?

**Comment by lyokha** [comment]
Hi, can you show output of command ``:imap``?

**Comment by lyokha** [comment]
Can you apply this patch:

```diff
--- xkbswitch.vim	2017-02-17 16:33:48.136597910 +0300
+++ /home/lyokha/.vim/plugin/xkbswitch.vim	2017-02-20 14:59:49.022244175 +0300
@@ -323,7 +323,9 @@
     redir => mappingsdump
     silent imap
     redir END
-    let mappings = split(mappingsdump, '\n')
+    let ff = empty(&ffs) ? &ff : split(&ffs, ',')[0]
+    let eol = ff == 'dos' ? '\r\n' : (ff == 'mac' ? '\r' : '\n')
+    let mappings = split(mappingsdump, eol)
     let mappingskeys = {}
     for mapping in mappings
         let mappingskeys[split(mapping)[1]] = 1
```

and test again? And show what is your ``:imap`` prints out?

**Comment by zdm** [comment]
I applied patch, but it had no effect.

:imap output is very large:
```
i  <C-S-PageDown> *@<C-O>:let b:xkb_skip_skey = 1<CR><C-S-PageDown>
i  <C-S-PageUp> *@<C-O>:let b:xkb_skip_skey = 1<CR><C-S-PageUp>
i  <C-S-Home>  *@<C-O>:let b:xkb_skip_skey = 1<CR><C-S-Home>
i  <C-S-End>   *@<C-O>:let b:xkb_skip_skey = 1<CR><C-S-End>
i  <C-S-Down>  *@<C-O>:let b:xkb_skip_skey = 1<CR><C-S-Down>
i  <C-S-Up>    *@<C-O>:let b:xkb_skip_skey = 1<CR><C-S-Up>
i  <C-S-Right> *@<C-O>:let b:xkb_skip_skey = 1<CR><C-S-Right>
i  <C-S-Left>  *@<C-O>:let b:xkb_skip_skey = 1<CR><C-S-Left>
i  <S-PageDown> *@<C-O>:let b:xkb_skip_skey = 1<CR><S-PageDown>
i  <S-PageUp>  *@<C-O>:let b:xkb_skip_skey = 1<CR><S-PageUp>
i  <S-Home>    *@<C-O>:let b:xkb_skip_skey = 1<CR><S-Home>
i  <S-End>     *@<C-O>:let b:xkb_skip_skey = 1<CR><S-End>
i  <S-Down>    *@<C-O>:let b:xkb_skip_skey = 1<CR><S-Down>
i  <S-Up>      *@<C-O>:let b:xkb_skip_skey = 1<CR><S-Up>
i  <S-Right>   *@<C-O>:let b:xkb_skip_skey = 1<CR><S-Right>
i  <S-Left>    *@<C-O>:let b:xkb_skip_skey = 1<CR><S-Left>
i  <3-LeftMouse> *@<C-O>V:<C-U>call <SNR>56_xkb_switch(1, 1)|normal
gv<CR><C-G>
i  <2-LeftMouse> *@<C-O>viw:<C-U>call <SNR>56_xkb_switch(1, 1)|normal
gv<CR><C-G>
i  <C-R>ю      *@<C-R>.
i  <C-R>Ж      *@<C-R>:
i  <C-R>№      *@<C-R>#
i  <C-R>Э      *@<C-R>"
i  <C-R>я      *@<C-R>z
i  <C-R>н      *@<C-R>y
i  <C-R>ч      *@<C-R>x
i  <C-R>ц      *@<C-R>w
i  <C-R>м      *@<C-R>v
i  <C-R>г      *@<C-R>u
i  <C-R>е      *@<C-R>t
i  <C-R>ы      *@<C-R>s
i  <C-R>к      *@<C-R>r
i  <C-R>й      *@<C-R>q
i  <C-R>з      *@<C-R>p
i  <C-R>щ      *@<C-R>o
i  <C-R>т      *@<C-R>n
i  <C-R>ь      *@<C-R>m
i  <C-R>д      *@<C-R>l
i  <C-R>л      *@<C-R>k
i  <C-R>о      *@<C-R>j
i  <C-R>ш      *@<C-R>i
i  <C-R>р      *@<C-R>h
i  <C-R>п      *@<C-R>g
i  <C-R>а      *@<C-R>f
i  <C-R>у      *@<C-R>e
i  <C-R>в      *@<C-R>d
i  <C-R>с      *@<C-R>c
<C-R>и      *@<C-R>b
i  <C-R>ф      *@<C-R>a
i  <C-Y>б       @<Plug>(emmet-expand-abbr)
i  <C-Y>ж       @<Plug>(emmet-expand-word)
i  <C-Y>г       @<Plug>(emmet-update-tag)
i  <C-Y>в       @<Plug>(emmet-balance-tag-inward)
i  <C-Y>В       @<Plug>(emmet-balance-tag-outword)
i  <C-Y>т       @<Plug>(emmet-move-next)
i  <C-Y>Т       @<Plug>(emmet-move-prev)
i  <C-Y>ш       @<Plug>(emmet-image-size)
i  <C-Y>.       @<Plug>(emmet-toggle-comment)
i  <C-Y>о       @<Plug>(emmet-split-join-tag)
i  <C-Y>л       @<Plug>(emmet-remove-tag)
i  <C-Y>ф       @<Plug>(emmet-anchorize-url)
i  <C-Y>Ф       @<Plug>(emmet-anchorize-summary)
i  \с          *@<C-O>:TComment<CR><C-O>j
i  \ыв         *@<Esc>:SrcDecompress<CR>
i  \ыс         *@<Esc>:SrcCompress<CR>
i  \ыщ         *@<Esc>:SrcObfuscate<CR>
i  <Plug>(emmet-anchorize-summary) *
<C-R>=emmet#util#closePopup()<CR><C-R>=emmet#anchorizeURL(1)<CR>
i  <Plug>(emmet-anchorize-url) *
<C-R>=emmet#util#closePopup()<CR><C-R>=emmet#anchorizeURL(0)<CR>
i  <Plug>(emmet-remove-tag) *
<C-R>=emmet#util#closePopup()<CR><C-R>=emmet#removeTag()<CR>
i  <Plug>(emmet-split-join-tag) * <Esc>:call emmet#splitJoinTag()<CR>
i  <Plug>(emmet-toggle-comment) *
<C-R>=emmet#util#closePopup()<CR><C-R>=emmet#toggleComment()<CR>
i  <Plug>(emmet-image-size) *
<C-R>=emmet#util#closePopup()<CR><C-R>=emmet#imageSize()<CR>
i  <Plug>(emmet-move-prev-item) * <Esc>:call emmet#moveNextPrevItem(1)<CR>
i  <Plug>(emmet-move-next-item) * <Esc>:call emmet#moveNextPrevItem(0)<CR>
i  <Plug>(emmet-move-prev) * <Esc>:call emmet#moveNextPrev(1)<CR>
i  <Plug>(emmet-move-next) * <Esc>:call emmet#moveNextPrev(0)<CR>
i  <Plug>(emmet-balance-tag-outword) * <Esc>:call emmet#balanceTag(-1)<CR>
i  <Plug>(emmet-balance-tag-inward) * <Esc>:call emmet#balanceTag(1)<CR>
i  <Plug>(emmet-update-tag) *
<C-R>=emmet#util#closePopup()<CR><C-R>=emmet#updateTag()<CR>
i  <Plug>(emmet-expand-word) *
<C-R>=emmet#util#closePopup()<CR><C-R>=emmet#expandAbbr(1,"")<CR>
i  <Plug>(emmet-expand-abbr) *
<C-R>=emmet#util#closePopup()<CR><C-R>=emmet#expandAbbr(0,"")<CR>
i  <Plug>TComment_<C-_>9 * <C-\><C-O>:call tcomment#SetOption("count",
9)<CR>
i  <Plug>TComment_<C-_>8 * <C-\><C-O>:call tcomment#SetOption("count",
8)<CR>
i  <Plug>TComment_<C-_>7 * <C-\><C-O>:call tcomment#SetOption("count",
7)<CR>
i  <Plug>TComment_<C-_>6 * <C-\><C-O>:call tcomment#SetOption("count",
6)<CR>
i  <Plug>TComment_<C-_>5 * <C-\><C-O>:call tcomment#SetOption("count",
5)<CR>
i  <Plug>TComment_<C-_>4 * <C-\><C-O>:call tcomment#SetOption("count",
4)<CR>
i  <Plug>TComment_<C-_>3 * <C-\><C-O>:call tcomment#SetOption("count",
3)<CR>
i  <Plug>TComment_<C-_>2 * <C-\><C-O>:call tcomment#SetOption("count",
2)<CR>
i  <Plug>TComment_<C-_>1 * <C-\><C-O>:call tcomment#SetOption("count",
1)<CR>
i  <Plug>TComment_<C-_>s * <C-O>:TCommentAs <C-R>=&ft<CR>_
i  <Plug>TComment_<C-_>n * <C-O>:TCommentAs <C-R>=&ft<CR><Space>
i  <Plug>TComment_<C-_>a * <C-O>:TCommentAs<Space>
i  <Plug>TComment_<C-_>b * <C-\><C-O>:TCommentBlock mode=#<CR>
i  <Plug>TComment_<C-_>i * <C-\><C-O>v:TCommentInline mode=#<CR>
i  <Plug>TComment_<C-_>r * <C-O>:TCommentRight<CR>
i  <Plug>TComment_<C-_><Space> * <C-O>:TComment<Space>
i  <Plug>TComment_<C-_>p * <C-O>:norm! m`vip<CR>:TComment<CR><C-O>``
i  <Plug>TComment_<C-_><C-_> * <C-O>:TComment<CR>
i  <F1>        * <C-O>:call ViewDoc('new', '<cword>')<CR>
i  <F6>        * <C-O>:Unite -buffer-name=helper -toggle
-prompt-direction=top -start-insert -no-restore menu:helper<CR>
i  <F5>        * <C-O>:Unite -buffer-name=session -toggle
-prompt-direction=top -hide-source-names session session/new<CR>
i  <S-Down>    * <C-O>gh<C-O>gj
i  <S-Up>      * <C-O>gh<C-O>gk
i  <Down>      * <C-O>gj
i  <Up>        * <C-O>gk
i  <F10>       * <C-O>:UndotreeToggle<CR>
i  <F8>        * <C-O>:Unite -buffer-name=outline -toggle -vertical
-direction=botright -winwidth=60 -start-insert -no-restore outline<CR>
i  <F3>        * <C-O>:Unite -buffer-name=MRU -toggle
-prompt-direction=top -start-insert -no-restore bookmark neomru/file<CR>
i  <F2>        * <C-O>:Unite -buffer-name=buffers -toggle
-prompt-direction=top -start-insert -no-restore buffer<CR>
i  <C-F4>      * <C-O><C-W>c
i  <C-Tab>     * <C-O><C-W>w
i  <S-Insert>    <C-V>
i  <ce><d4>      <C-R><C-O>*
!  <ce>u         <C-End>
!  <ce>w         <C-Home>
i  <C-A>       * <C-O>gg<C-O>gH<C-O>G
i  <NL>        * <Esc>:-tabm<CR>a
i  <C-K>       * <Esc>:+tabm<CR>a
i  <C-S>       * <C-O>:update<CR>
i  <C-V>       & <C-G>ux<BS><Esc>:call paste#Paste()<CR>gi
i  <C-Y>A        <Plug>(emmet-anchorize-summary)
i  <C-Y>a        <Plug>(emmet-anchorize-url)
i  <C-Y>k        <Plug>(emmet-remove-tag)
i  <C-Y>j        <Plug>(emmet-split-join-tag)
i  <C-Y>/        <Plug>(emmet-toggle-comment)
i  <C-Y>i        <Plug>(emmet-image-size)
i  <C-Y>N        <Plug>(emmet-move-prev)
i  <C-Y>n        <Plug>(emmet-move-next)
i  <C-Y>D        <Plug>(emmet-balance-tag-outword)
i  <C-Y>d        <Plug>(emmet-balance-tag-inward)
i  <C-Y>u        <Plug>(emmet-update-tag)
i  <C-Y>;        <Plug>(emmet-expand-word)
i  <C-Y>,        <Plug>(emmet-expand-abbr)
i  <C-Y>       * <C-O><C-R>
i  <C-Z>       * <C-O>u
i  \so         * <Esc>:SrcObfuscate<CR>
i  \sc         * <Esc>:SrcCompress<CR>
i  \sd         * <Esc>:SrcDecompress<CR>
i  \c          * <C-O>:TComment<CR><C-O>j
```

**Comment by lyokha** [comment]
Looks good at first glance, except for

```
<C-R>и *@<C-R>b
```

Here there is no ``i`` at the beginning, but i suspect that you just missed it when copied and pasted the output, correct?

**Comment by zdm** [comment]
yes, seems, that this is due to incorrect copy/paste

**Comment by lyokha** [comment]
Please comment ``let g:XkbSwitchIMappings = ['ru']`` in your *.vimrc* and run vim again, does it help?

**Comment by zdm** [comment]
yes, it helped.

**Comment by lyokha** [comment]
ok, then the reason is in *IMappings*, then i need to carefully read through all your ``imap``'s and find what kind of them the plugin does not parse well.

**Comment by zdm** [comment]
Thank you.
Tell me, if I can help somehow.

**Comment by lyokha** [comment]
Yes, could you again disable ``let g:XkbSwitchIMappings = ['ru']`` and show how looks output of ``:imap`` in this case (it must be shorter).

**Comment by zdm** [comment]
i  <Plug>(emmet-anchorize-summary) *
<C-R>=emmet#util#closePopup()<CR><C-R>=emmet#anchorizeURL(1)<CR>
i  <Plug>(emmet-anchorize-url) *
<C-R>=emmet#util#closePopup()<CR><C-R>=emmet#anchorizeURL(0)<CR>
i  <Plug>(emmet-remove-tag) *
<C-R>=emmet#util#closePopup()<CR><C-R>=emmet#removeTag()<CR>
i  <Plug>(emmet-split-join-tag) * <Esc>:call emmet#splitJoinTag()<CR>
i  <Plug>(emmet-toggle-comment) *
<C-R>=emmet#util#closePopup()<CR><C-R>=emmet#toggleComment()<CR>
i  <Plug>(emmet-image-size) *
<C-R>=emmet#util#closePopup()<CR><C-R>=emmet#imageSize()<CR>
i  <Plug>(emmet-move-prev-item) * <Esc>:call emmet#moveNextPrevItem(1)<CR>
i  <Plug>(emmet-move-next-item) * <Esc>:call emmet#moveNextPrevItem(0)<CR>
i  <Plug>(emmet-move-prev) * <Esc>:call emmet#moveNextPrev(1)<CR>
i  <Plug>(emmet-move-next) * <Esc>:call emmet#moveNextPrev(0)<CR>
i  <Plug>(emmet-balance-tag-outword) * <Esc>:call emmet#balanceTag(-1)<CR>
i  <Plug>(emmet-balance-tag-inward) * <Esc>:call emmet#balanceTag(1)<CR>
i  <Plug>(emmet-update-tag) *
<C-R>=emmet#util#closePopup()<CR><C-R>=emmet#updateTag()<CR>
i  <Plug>(emmet-expand-word) *
<C-R>=emmet#util#closePopup()<CR><C-R>=emmet#expandAbbr(1,"")<CR>
i  <Plug>(emmet-expand-abbr) *
<C-R>=emmet#util#closePopup()<CR><C-R>=emmet#expandAbbr(0,"")<CR>
i  <Plug>TComment_<C-_>9 * <C-\><C-O>:call tcomment#SetOption("count",
9)<CR>
i  <Plug>TComment_<C-_>8 * <C-\><C-O>:call tcomment#SetOption("count",
8)<CR>
i  <Plug>TComment_<C-_>7 * <C-\><C-O>:call tcomment#SetOption("count",
7)<CR>
i  <Plug>TComment_<C-_>6 * <C-\><C-O>:call tcomment#SetOption("count",
6)<CR>
i  <Plug>TComment_<C-_>5 * <C-\><C-O>:call tcomment#SetOption("count",
5)<CR>
i  <Plug>TComment_<C-_>4 * <C-\><C-O>:call tcomment#SetOption("count",
4)<CR>
i  <Plug>TComment_<C-_>3 * <C-\><C-O>:call tcomment#SetOption("count",
3)<CR>
i  <Plug>TComment_<C-_>2 * <C-\><C-O>:call tcomment#SetOption("count",
2)<CR>
i  <Plug>TComment_<C-_>1 * <C-\><C-O>:call tcomment#SetOption("count",
1)<CR>
i  <Plug>TComment_<C-_>s * <C-O>:TCommentAs <C-R>=&ft<CR>_
i  <Plug>TComment_<C-_>n * <C-O>:TCommentAs <C-R>=&ft<CR><Space>
i  <Plug>TComment_<C-_>a * <C-O>:TCommentAs<Space>
i  <Plug>TComment_<C-_>b * <C-\><C-O>:TCommentBlock mode=#<CR>
i  <Plug>TComment_<C-_>i * <C-\><C-O>v:TCommentInline mode=#<CR>
i  i  <Plug>TComment_<C-_>r * <C-O>:TCommentRight<CR>
i  <Plug>TComment_<C-_><Space> * <C-O>:TComment<Space>
i  <Plug>TComment_<C-_>p * <C-O>:norm! m`vip<CR>:TComment<CR><C-O>``
i  <Plug>TComment_<C-_><C-_> * <C-O>:TComment<CR>
i  <F1>        * <C-O>:call ViewDoc('new', '<cword>')<CR>
i  <F6>        * <C-O>:Unite -buffer-name=helper -toggle
-prompt-direction=top -start-insert -no-restore menu:helper<CR>
i  <F5>        * <C-O>:Unite -buffer-name=session -toggle
-prompt-direction=top -hide-source-names session session/new<CR>
i  <S-Down>    * <C-O>gh<C-O>gj
i  <S-Up>      * <C-O>gh<C-O>gk
i  <Down>      * <C-O>gj
i  <Up>        * <C-O>gk
i  <F10>       * <C-O>:UndotreeToggle<CR>
i  <F8>        * <C-O>:Unite -buffer-name=outline -toggle -vertical
-direction=botright -winwidth=60 -start-insert -no-restore outline<CR>
i  <F3>        * <C-O>:Unite -buffer-name=MRU -toggle
-prompt-direction=top -start-insert -no-restore bookmark neomru/file<CR>
i  <F2>        * <C-O>:Unite -buffer-name=buffers -toggle
-prompt-direction=top -start-insert -no-restore buffer<CR>
i  <C-F4>      * <C-O><C-W>c
i  <C-Tab>     * <C-O><C-W>w
i  <S-Insert>    <C-V>
i  <ce><d4>      <C-R><C-O>*
!  <ce>u         <C-End>
!  <ce>w         <C-Home>
i  <C-A>       * <C-O>gg<C-O>gH<C-O>G
i  <NL>        * <Esc>:-tabm<CR>a
i  <C-K>       * <Esc>:+tabm<CR>a
i  <C-S>       * <C-O>:update<CR>
i  <C-V>       & <C-G>ux<BS><Esc>:call paste#Paste()<CR>gi
i  <C-Y>A        <Plug>(emmet-anchorize-summary)
i  <C-Y>a        <Plug>(emmet-anchorize-url)
i  <C-Y>k        <Plug>(emmet-remove-tag)
i  <C-Y>j        <Plug>(emmet-split-join-tag)
i  <C-Y>/        <Plug>(emmet-toggle-comment)
i  <C-Y>i        <Plug>(emmet-image-size)
i  <C-Y>N        <Plug>(emmet-move-prev)
i  <C-Y>n        <Plug>(emmet-move-next)
i  <C-Y>D        <Plug>(emmet-balance-tag-outword)
i  <C-Y>d        <Plug>(emmet-balance-tag-inward)
i  <C-Y>u        <Plug>(emmet-update-tag)
i  <C-Y>;        <Plug>(emmet-expand-word)
i  <C-Y>,        <Plug>(emmet-expand-abbr)
i  <C-Y>       * <C-O><C-R>
i  <C-Z>       * <C-O>u
i  \so         * <Esc>:SrcObfuscate<CR>
i  \sc         * <Esc>:SrcCompress<CR>
i  \sd         * <Esc>:SrcDecompress<CR>
i  \c          * <C-O>:TComment<CR><C-O>j

**Comment by lyokha** [comment]
I do not see any issues with imap translation, actually it works fine. Probably you have some wrong definitions of imaps in you *.vimrc* (see related solution [here](http://stackoverflow.com/a/16406044/5655455)). Actually *vim-xkbswitch* calls command ``imap`` when it translates *IMappings*: it makes it using Vim's command ``redir`` which itself is not safe though. But it do it only once whereas you have multiple lines of the *No mapping found* message, and this is really strange.

**Comment by zdm** [comment]
Ok, i will check vimrc

**Comment by lyokha** [comment]
Please try the next patch:

```diff
--- plugin/xkbswitch.vim	2017-02-20 21:32:22.476482300 +0300
+++ /home/lyokha/.vim/plugin/xkbswitch.vim	2017-02-20 22:13:26.640931328 +0300
@@ -340,6 +340,19 @@
                 continue
             endif
             let data = split(mapping)
+            if data[0] != 'i' || len(data) < 3
+                    echoerr "Line '".mapping."' does not look like an imap ".
+                                \ "value, another plugin is supposedly ".
+                                \ "doing 'redir'!"
+                continue
+            endif
+            let mapval = maparg(data[1], 'i')
+            if empty(mapval)
+                    echoerr "Line '".mapping."' does not look like an imap ".
+                                \ "value, another plugin is supposedly ".
+                                \ "doing 'redir'!"
+                continue
+            endif
             " do not duplicate <Plug> and <SNR> mappings
             " (when key starts with '<Plug>' or '<SNR>')
             if match(data[1], '^\c\%(<Plug>\|<SNR>\)') != -1
```

I wonder if you'll see messages about parallel ``redir``.

**Comment by zdm** [comment]
I got an error:

```
Error detected while processing function
<SNR>56_load_all[6]..<SNR>56_imappings_load:
line   37:
Line 'i  <ce><d4>      <C-R><C-O>*' does not look like an imap value,
another plugin is supposedly doing 'redir'!
line   30:
Line '!  <ce>u         <C-End>' does not look like an imap value,
another plugin is supposedly doing 'redir'!
Line '!  <ce>w         <C-Home>' does not look like an imap value,
another plugin is supposedly doing 'redir'!
```

**Comment by lyokha** [comment]
Please try the new version, now it won't complain (because referring to redir was erroneous) and check by ``:imap`` that all your maps got translated (including ``<ce>u`` -> ``<ce>г`` and ``<ce>w`` -> ``<ce>ц``). If everything is OK then we can close the bug.

**Comment by zdm** [comment]
I tested, everything works without issues.
Thank you!

**Comment by lyokha** [comment]
Thanks for cooperation!
