### ISSUE TITLE
Типографская раскладка Бирмана

### ISSUE THREAD

**Issue by Realetive** [lyokha/vim-xkbswitch#34]
Системные раскладки заменены на http://ilyabirman.ru/projects/typography-layout/, установлены https://github.com/myshov/xkbswitch-macosx и https://github.com/myshov/libxkbswitch-macosx.
При english-раскладке команда
```:echo libcall('/usr/local/lib/libxkbswitch.dylib', 'Xkb_Switch_getXkbLayout', '')```
возвращает `2`, при русской, соответсвенно — 1. Корректно работают
```
:echo libcall('/usr/local/lib/libxkbswitch.dylib', 'Xkb_Switch_setXkbLayout', '1')
:echo libcall('/usr/local/lib/libxkbswitch.dylib', 'Xkb_Switch_setXkbLayout', '2')
```
устанавливая русскую и английскую раскладки.
В `.vimrc` (_vim-xkbswitch_ установлен через Vundle):

```
let g:XkbSwitchEnabled = 1
let g:XkbSwitchLib = '/usr/local/lib/libxkbswitch.dylib'
let g:XkbSwitchIMappings = ['ru']
let g:XkbSwitchDynamicKeymap = 1
let g:XkbSwitchKeymapNames = {'1' : 'russian-jcukenwin'}

set keymap=russian-jcukenwin
set iminsert=0
set imsearch=0
```

Что ещё я упускаю? Не работает ни автомаппинг, ни возврат к предыдущей раскладке при выходе из Insert-mode.

**Comment by lyokha** [comment]
Попробуйте

```vim
let g:XkbSwitchKeymapNames = {'ru' : 'russian-jcukenwin'}
```

(вместо `'1' : 'russian-jcukenwin'`).

**Comment by lyokha** [comment]
Так у вас раскладки называются `1` и `2`? Тогда мой предыдущий совет не годится, зато нужно заменить установку маппингов на

```vim
let g:XkbSwitchIMappings = ['1']
```
, создать файл c соответствующим маппингом по типу *xkbswitch.tr* и загружать уго c помощью переменной *g:XkbSwitchIMappingsTrData* (это должно быть описано в документации).

**Comment by Realetive** [comment]
```
let g:XkbSwitchKeymapNames = {'ru' : 'russian-jcukenwin'}
```
помогло тем, что по Esc раскладка ставится в en для Normal-mode. А вот для Ctrl-c — не работает.

А после
```
let g:XkbSwitchIMappings = ['1']
```
выдало:
![2017-08-14 15 21 18](https://user-images.githubusercontent.com/2073959/29271501-7241890e-8104-11e7-8d2d-b275d610b23c.png)

**Comment by lyokha** [comment]
Для `Ctrl-C` он и не будет работать, насколько я помню, там какая-то проблема c перехватом этой последовательности в vim. А c раскладкой *1* создайте файл с именем, например *xkbswitch.tr* и введите в него вашу раскладку:

```
1  Birman layout
<   qwertyuiop[]asdfghjkl;'zxcvbnm,.`/QWERTYUIOP{}ASDFGHJKL:"ZXCVBNM<>?~@#$^&|
>   йцукенгшщзхъфывапролджэячсмитьбюё.ЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ,Ё"№;:?/
```

Вместо оригинального *ru* здесь поставлена *1* - это важно (хотя, если 1 у вас - это оригинальная английская раскладка, то нужно поставить здесь *2*), предложение *Birman layout* - просто комментарий, можете написать сюда все что хотите, или не писать ничего). B самое главное, у вас должно быть соответствие между символами оригинальной английской раскладки и вашей кастомной (то есть порядок символов после тега *>* у вас будет другой).

После правильной настройки файла *xkbswitch.tr* нужно сослаться на него в *.vimrc*:

```vim
let g:XkbSwitchIMappingsTrData = xkbswitch.tr
```

(возможно c полным путем к файлу).

**Comment by Realetive** [comment]
Сделал. теперь так:
```
" .vimrc

let g:XkbSwitchEnabled = 1
let g:XkbSwitchLib = '/usr/local/lib/libxkbswitch.dylib'
let g:XkbSwitchIMappings = ['1']
let g:XkbSwitchIMappingsTr = {
          \ '1':
          \ {'<': 'qwertyuiop[]asdfghjkl;''zxcvbnm,.`/'.
          \       'QWERTYUIOP{}ASDFGHJKL:"ZXCVBNM<>?~@#$^&|',
          \  '>': 'йцукенгшщзхъфывапролджэячсмитьбюё.'.
          \       'ЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ,Ё"№;:?/'}
          \ }
let g:XkbSwitchIMappingsTrData = $HOME.'/.vim/plugins/xkbswitch/xkbswitch.tr'
let g:XkbSwitchDynamicKeymap = 1
let g:XkbSwitchKeymapNames = {'1' : 'russian-jcukenwin'}

set keymap=russian-jcukenwin
set iminsert=0
set imsearch=0
```

в `~/.vim/plugins/xkbswitch/xkbswitch.tr`:
```
1  Russian Birman layout 
< qwertyuiop[]asdfghjkl;'zxcvbnm,.`/QWERTYUIOP{}ASDFGHJKL:"ZXCVBNM<>?~@#$^&|
> йцукенгшщзхъфывапролджэячсмитьбюё.ЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ,Ё"№;:?/
```
Теперь все работает 👍 

А неработающий Ctrl-c решил `:inoremap jj <ESC>`

**Comment by lyokha** [comment]
Ну или так )) Но если вы определили переменную `g:XkbSwitchIMappingsTr` в .vimrc, то переменная `g:XkbSwitchIMappingsTrData` вам больше не нужна, да и сам файл *xkbswitch.tr* тоже. Только я понять не могу, где здесь специфичная настройка раскладки Бирмана проявляется?

**Comment by Realetive** [comment]
Нигде, по идее. Там новые маппинги на `Alt+_` появляются, а всё остальное стандартное.

**Comment by lyokha** [comment]
А, ок. Я так и понял, когда прочитал, что это такое :)

**Comment by Realetive** [comment]
Кажется, поспешил с выводами. Правильно ли я понимаю, что если, например, я в Normal-mode нажимаю `д`, то это автоматически должно интерпретироваться как `l`?

**Comment by lyokha** [comment]
Нет, неправильно, это *Insert-mode маппинги*, они относятся только к режиму ввода. Вообще, этот модуль был задуман c той целью, чтобы в Нормальном режиме у пользователя всегда была оригинальная (обычно английская) раскладка. Если вы оказались после выхода из режима ввода в нормальный режим в русской раскладке, то это либо данный модуль не совсем корректно работает, либо он не подходит для вашего специфичного сценария.

**Comment by Realetive** [comment]
А, ну тогда действительно всё в порядке 👍 
Ещё раз спасибо!

**Comment by lyokha** [comment]
Кстати, если вы хотите гарантировать оригинальную раскладку в Нормальном режиме после возращения из режима Ввода, то можете установить в .vimrc

```vim
let g:XkbSwitchNLayout = 'us'
```

Толко в вашем случае вместо *'us'* надо написать *'1'*  или *'2'*.
