### ISSUE TITLE
Смена расскладки при r{char}

### ISSUE THREAD

**Issue by dahek** [lyokha/vim-xkbswitch#38]
Иногда возникает необходимость исправить одну букву в строке и я использую для этого комманду r{char}. При этом смена раскладки не происходит. Хотелось бы иметь такую фичу.

**Comment by lyokha** [comment]
Смотрите [Keymap assistance in Normal mode](https://github.com/lyokha/vim-xkbswitch#keymap-assistance-in-normal-mode). Суть такова. Устанавливаете в *.vimrc*

```vim
let g:XkbSwitchAssistNKeymap = 1
```

и теперь команды `r` и `f` будут использовать символы раскладки, которая была установлена в Insert mode в предыдущий раз.
