### ISSUE TITLE
How to use vim-xkbswitch with i3wm?

### ISSUE THREAD

**Issue by sepremento** [lyokha/vim-xkbswitch#57]
Began using i3wm, configured switching keyboard layout with this i3 config:

```
exec --no-startup-id setxkbmap -layout us,ru
exec --no-startup-id setxkbmap -option 'grp:shifts_toggle'
```

If I get this correctly, each time i3 starts those two `setxkbmap` commands are executed. Except now vim-xkbswitch does not switch keyboard layout while changing modes. I understand everything that contains xkb in it very poorly. Where can I look for help? Maybe there are solutions for aligning i3wm and xkbswitch?

**Comment by sepremento** [comment]
I think I've managed to introduce them to each other with this repo [Zebradil/xkb-switch-i3](https://github.com/Zebradil/xkb-switch-i3). Then added to i3 config:

```
exec-always --no-startup-id xkb-switch --i3
```

**Comment by lyokha** [comment]
That's cool! I did not know about this switcher, I should add this into the list of pluggable backend libraries in the Readme.
