### ISSUE TITLE
Can't restore Normal mode keyboard layout when leaving search '/' mode

### ISSUE THREAD

**Issue by Rom888** [lyokha/vim-xkbswitch#60]
Добрый день!
Не получается настроить чтобы в нормальном режиме после выхода из поиска восстанавливалась английская раскладка, то есть сценарий такой:
в нормальном режиме, раскладка 'us'
нажимаю '/' для поиска
переключаю раскладку на 'ru' и ввожу русские символы, 
затем нажимаю 'enter' vim находит текст и возвращается в нормальный режим
далее в нормальном режиме раскладка остается 'ru', а хотелось бы чтобы она автоматом возвращалась на 'us', как это происходит при выходе из insert mode.

ubuntu 22.04.01
gvim 8.2.4919
```
gdbus call --session --dest org.gnome.Shell --object-path /org/g3kbswitch/G3kbSwitch --method org.g3kbswitch.G3kbSwitch.List
(true, '[{"key":"0","value":"us"},{"key":"1","value":"ru"}]')
```
.vimrc:
```
let g:XkbSwitchEnabled = 1 
let g:XkbSwitchIMappings = ['ru']
let g:XkbSwitchNLayout = 'us'
let g:XkbSwitchAssistSKeymap = 1
let g:XkbSwitchLib = '/usr/local/lib/libg3kbswitch.so'
```

**Comment by lyokha** [comment]
Это не реализовано. В vim просто нет соответствующих автокоманд, на которые можно было бы повесить функциональность переключения раслкладки при выполнении команды `f`.

Но вы можете настроить ручной переключатель раскладок, при включенном `g:XkbSwitchAssistSKeymap`:

```vim
" quickly toggle keyboard layout for f and r commands in normal mode
" (<C-^> also switches keyboard layout in search mode)
let g:XkbSwitchIminsertToggleKey = '<C-^>'
let g:XkbSwitchIminsertToggleEcho = 0
```
Понятно, что ручное переключение не очень-то удобно, но пока только так. Статусная строка `airline`, кстати говоря, поддерживает отображение текущей раскладки для этого случая из коробки (секция `keymap`).

**Comment by lyokha** [comment]
Заметил, что у вас нет настройки

```vim
let g:XkbSwitchAssistNKeymap = 1
```

Это для `f` и `r` команд - ее нужно включить. Сейчас у вас включена `g:XkbSwitchAssistSKeymap` - это для строк поиска.

Пока исследовал вашу проблему, обнаружил, что в новом vim есть автокоманды `CmdlineEnter` и `CmdlineLeave`, которых не было, когда плагин активно разрабатывался. Это значит, что `g:XkbSwitchAssistSKeymap` можно заменить на полноценную поддержку переключения раскладок при входе и выходе из строки поиска. Пожалуй, это я сделаю (к тому же уже проверил, что оно работает). К сожалению, автокоманд для триггеринга команды `f` по-прежнему нет.

**Comment by Rom888** [comment]
Спасибо за отклик.
> Но вы можете настроить ручной переключатель раскладок, при включенном g:XkbSwitchAssistSKeymap:
Не очень понимаю зачем, ведь я могу переключиться обратно на 'us' стандартным образом (у меня настроен правый ctrl).

> Сейчас у вас включена g:XkbSwitchAssistSKeymap - это для строк поиска.
Пока у меня это не работает, или я не до конца понимаю как это должно работать.
Сейчас так:
Normal mode
нажимаю 'i', перехожу в insert mode
переключаюсь на 'ru', ввожу текст
нажимаю 'esc' возвращаюсь в normal mode
нажимаю '/' и начинаю вводить символы для поиска - и обнаруживаю что раскладка 'us'
хотя если я правильно понимаю, при g:XkbSwitchAssistSKeymap = 1 у меня должна остаться раскладка которая была последней при выходе из insert mode

> Пожалуй, это я сделаю (к тому же уже проверил, что оно работает)
Это будет здорово!
А в neovim такая же история? Подумываю на него перейти, но пока не решился.

**Comment by lyokha** [comment]
Я закоммитил решение для строк поиска, теперь у них полная поддержка отслежки переключения, такая же как в Insert mode. Это будет работать если у вас vim 8.1 и выше или neovim. Соответственно, переменная `g:XkbSwitchAssistSKeymap` теперь deprecated (vim будет ругаться, удалите ее из конфига).

Для keymap assistance команд `f` и `r` вам реально нужна другая переменная `g:XkbSwitchAssistNkeymap`. Полная поддержка переключения раскладки для этих команд не работает, поскольку невозможно поймать событие аосле ввода символа поиска (или замены для команды `r`).

Но зато работает keymap assistance. Суть его в следующем. Допустим вы редактировали что-то в режиме ввода на русской раскладке, вышли из него, теперь когда вы введете `f` и символ за ним, этот символ будет русский, даже несмотря на то, что системная раскладка будет показывать английский (но airline при этом будет показывать русский!). В следующий раз после выхода из режима ввода, будет запомнена последняя раскладка снова, и это отразиться на командах `f` и `r`, а также в статусе airline. Если вы не хотите переключать keymap assistance входом и выходом в режим ввода, то можете просто ввести `<C-^>` в нормальном режиме - раскладка для этих команд переключится.

Раньше, до последнего коммита, управлять раскладкой в строке поиска можно было тоже только таким вычурным способом, но теперь она поддерживается напрямую и работает совместно с режимом ввода.

**Comment by Rom888** [comment]
Обновил до последней версии vim-xkbswitch, все работает шикарно, это прямо радует, т.к. раньше после поиска не на латинице всегда были проблемы, т.к. мозг думал что все само переключится обратно.
f и r раньше не использовал, и с такими нюансами, думаю не буду пока их использовать тоже.

Большое спасибо за этот проект и связанные с ним, здорово помогают!

**Comment by lyokha** [comment]
> Это будет здорово! А в neovim такая же история? Подумываю на него перейти, но пока не решился.

В neovim плагин работает точно так же как в vim. Я сам перешел на neovim почти год назад. Не могу нарадоваться )) Две киллер-фичи neovim, которых нет в vim, лично для меня, это встроенная поддержка LSP и tree-sitter. То, что настройки можно писать на lua наерное тоже хорошо, но первые две фичи - это просто сокровище, делающее vim полноценным IDE, при этом глубоко конфигурируемым. В общем, очень рекомендую именно neovim.
