### ISSUE TITLE
Не удается заставить работать на Ubuntu 22.10

### ISSUE THREAD

**Issue by alant1t** [lyokha/vim-xkbswitch#64]
Приветствую!
Пытаюсь запустить Ваш плагин в vim, но он не работает
(Ubuntu 22.10, GNOME Shell 43.1, Vim 9.0).

g3kb-switch собрался и установился. На проверки, указанные в [инструкции](https://github.com/lyokha/g3kb-switch), дает рабочие ответы.

В `~/.vimrc` нужные строки внесены.

Проверки, указанные в секции [Troubleshooting](https://github.com/lyokha/vim-xkbswitch#troubleshooting), тоже проходит.

Но при выходе из Insert-mode в Normal-mode не переключает с русской раскладки на английскую.

Также, когда пытаюсь запустить плагин в рантайме командой `:EnableXkbSwitch`, vim выдает следующую ошибку
`E492: Not an editor command: EnableXkbSwitch`

**Comment by lyokha** [comment]
> Также, когда пытаюсь запустить плагин в рантайме командой :EnableXkbSwitch, vim выдает следующую ошибку
E492: Not an editor command: EnableXkbSwitch

Это интересный момент. Вы уверены что плагин действительно установлен? Такая ошибка намекает, что плагин не был загружен на старте, например, скрипт с плагином  не находится в `$VIMRUNTIME`.

Что говорит

```vim
:mess
```

?

**Comment by alant1t** [comment]
```:mess```
дает такой ответ:
`Messages maintainer: Bram Moolenaar <Bram@vim.org>  `

**Comment by alant1t** [comment]
> Такая ошибка намекает, что плагин не был загружен на старте, например, скрипт с плагином не находится в $VIMRUNTIME.

А как его туда поместить?)

**Comment by lyokha** [comment]
Ок, вам надо убедиться, что плагин установлен. В случае `vim`, в директории `~/.vim/plugin` должен находиться файл `xkbswitch.vim`.

> А как его туда поместить?)

Собственно, установить плагин. Для этого есть много разных способов. Лично я пользуюсь `vim-plug` и для установки vim-xkbswitch нужно поместить в `.vimrc` строки

```vim
call plug#begin()
Plug 'lyokha/vim-xkbswitch'
call plug#end()
```

Смотрите документацию в https://github.com/junegunn/vim-plug о том как установить сам vim-plug и как устанавливать и обновлять другие плагины.

Или просто скопируйте файл `plugin/xkbswitch.vim` из этого репозитория в директорию `~/.vim/plugin`.

**Comment by alant1t** [comment]
Огромное спасибо! Прошу прощения за мой тупняк
