### ISSUE TITLE
FreeBSD и возврат к редактору

### ISSUE THREAD

**Issue by sergDash** [lyokha/vim-xkbswitch#71]
Два вопросика.

1. Вот тут не очень понял условия (не знаю языка vim)

if !has('macunix') && has('unix') && empty($DISPLAY) && empty($SWAYSOCK)

просто заменил на

if empty($DISPLAY)
    let g:XkbSwitchEnabled = 0
else
    let g:XkbSwitchEnabled = 1
endif

не нашел где включается плагин в работу

2. Хотелось бы чтобы при получении фокуса и нормальном режиме vim, он снова бы включал en раскладку. Потому что ушел в другое окно, там переключил раскладку, вернулся в vim и нажимая / для поиска, по факту нажимаю точку и порчу текст. И еще нюанс что оконный менеджер dwm, фокус при наведении мышки без клика. Так что повесить такое на клик может быть не вариант.

**Comment by lyokha** [comment]
1. По идее, достаточно указать `let g:XkbSwitchEnabled = 1` в .vimrc, изменять код плагина не нужно (здесь вы наоборот упростили условие для его отключения).
2. Обычно в оконных менеджерах есть настройка *Отдельная раскладка для каждого окна*, чекните ее и раскладка будет возвращаться при врозврате к окну с vim. В любом случае, vim не сможет ловить клик по окну, так как это событие обрабатывает оконный менеджер. Хотя в vim есть обработчик получения фокуса, вариант с отдельной раскладкой для каждого окна мне кажется более естественным (сам использую это в Fedora/Mate).

**Comment by lyokha** [comment]
Нашел патч для dwm, который делает раскладку клавиатуры привязанной к окну: /https://dwm.suckless.org/patches/pwkl/

**Comment by sergDash** [comment]
Спасибо большое! Вернул условие, прописал в .vimrc строчку (не дочитал мануал), поставил патч на dwm и все прекрасно.

Ну почти :). Нашел еще парочку затыков.

1. Если в консоли набрал vim ~/русский то изначально кнопки не работают
2. Если в vim набрал :e ~/русский то тоже теряет кнопки

Нужно попереключать раскладку чтобы сцепление заработало.

**Comment by lyokha** [comment]
1. добавьте строку `let g:XkbSwitchNLayout = 'us'` в .vimrc (это установит начальную раскладку в нормальном режиме в *us*).
2. тоже должно работать после изменения из первого пункта.

**Comment by sergDash** [comment]
При :w и при ошибке "несохраненные данные" при выполнении :e

**Comment by lyokha** [comment]
да, действительно, сделайте такое изменеие в plugin/xkbswitch.vim:

```diff
-                autocmd CmdlineLeave /,\?
+                autocmd CmdlineLeave /,\?,:
```

(то есть добавьте запятую и двоеточие в паттерне в строке с `autocmd CmdlineLeave`). Дожно заработать, если заработает, я закоммичу изменение.

**Comment by sergDash** [comment]
Да, все отлично. Теперь совсем удобно работать!
